# Generated by Django 4.1.9 on 2023-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("record_id", models.CharField(max_length=36)),
                ("title", models.CharField(blank=True, max_length=250)),
                ("scope_content_description", models.JSONField(blank=True)),
                ("citable_reference", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
