# Generated by Django 4.1.9 on 2023-05-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover_records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="id",
        ),
        migrations.AlterField(
            model_name="record",
            name="record_id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
