# Generated by Django 4.1.9 on 2023-05-08 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover_records", "0003_alter_record_scope_content_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="record_id",
            new_name="id",
        ),
    ]
