# Generated by Django 4.1.9 on 2023-05-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover_records", "0004_rename_record_id_record_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="scope_content_description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
